### ISSUE TITLE
Nytt endepunkt for kommentar til en spesifikk kontroller

### ISSUE THREAD

**Issue by malinnsnieske** [kartverket/regelrett#263]
Lage et nytt endepunkt for å hente ut kommentarene til en kontroller basert på id. Noe i duren av "comments/teamID/kontrollerID". Dette vil gjøre det enklere å kun fetche nødvendige kommentarer til siden.

**Comment by starheim98** [comment]
https://github.com/kartverket/regelrett/issues/264#issuecomment-2367597589

kommentaren gjelder denne også
