### ISSUE TITLE
Nytt endepunkt for svar til en spesifikk kontroller

### ISSUE THREAD

**Issue by malinnsnieske** [kartverket/regelrett#264]
Lage et nytt endepunkt for å hente ut svarene til en kontroller basert på id. Noe i duren av "answers/teamID/kontrollerID". Dette vil gjøre det enklere å kun fetche nødvendige svar til siden.

**Comment by starheim98** [comment]
Trenger vi å dele opp i så mange endepunker? Kan det være nok å kun fetche en spesifikk kontroller med tilhørende svar og kommentarer?

**Comment by starheim98** [comment]
Dropper denne da det holder å kun fetche en spesifikk rad
