### ISSUE TITLE
Endre navn fra Svar til answer

### ISSUE THREAD

**Issue by malinnsnieske** [kartverket/regelrett#275]
Nå brukes "Svar" og "answer" om hverandre som skaper mye forvirring og unødvendige bugs. 
Rename Svar til answer i hele repoet.

**Comment by starheim98** [comment]
Skal vel fortsatt stå "Svar" i frontend? 🤔

**Comment by malinnsnieske** [comment]
@starheim98 Ja, bare endre i typene. I AnswerType i frontend har vi f.eks. questionId, updated, comment og Svar. Så endre det til answer, men ikke i UI nei
