### ISSUE TITLE
Gjøre Regelrett kontekst-agnostisk

### ISSUE THREAD

**Issue by chribjel** [kartverket/regelrett#346]
I samtale med Jobi etter standup:

Regelrett skal ikke vite hvilken kontekst skjemaet blir utfylt for.

Eksempel:

1. Bruker går inn i Funksjonsregisteret, fordi hen skal fylle ut SLA/SLO
2. Funksjonsregisteret lar sin flyt inn til regelrett.

funkreg/func/{func-id} lenker til regelrett/skjema/{skjema_id}/kontekst/{guid} der guid er en globalt unik id som funksjonsregisteret holder styr på. Funksjonsregisteret lagrer mappingen i sin database. (regelrett_guid, func_id) for å kunne finne tilbake til skjema.

Regelrett lagrer kun på (kontekst_guid, skjema_id, spm_id, svar) og vet ingenting om hvilken kontekst svar.

## Hva må gjøres

1. Landingssiden skal i utgangspunktet vekk fra Regelrett, ettersom andre tjenester lager sine veier inn til Regelrett.
2. Databasen oppdateres slik at funksjon ikke er et konsept, og vi trenger ikke lengere snakke med FRISK, men heller FRISK snakker med Regelrett.

Dette burde forenkle Regelrett-systemet drastisk, men krever en del refaktorering.
```[tasklist]
### Tasks
- [ ] https://github.com/kartverket/regelrett/issues/350
- [ ] https://github.com/kartverket/regelrett/issues/351
```

**Comment by perzonas** [comment]
@chribjel Utvikle denne description lit for andre

**Comment by chribjel** [comment]
Jobber med saken @perzonas !
